### ISSUE TITLE
to discuss on 2024-01-16

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-data#137]
## urgent open issues re bugs (@linxOD):
- [x] search not working for Auden documents, date range cannot be altered, eg "Christiane", "Burgomeister" - https://github.com/Auden-Musulin-Papers/amp-app/issues/114#issue-2062168784
- [x] double representation of XML characters in web app, eg lines after poem - https://github.com/Auden-Musulin-Papers/amp-app/issues/113#issue-2062150340
- [x] poetry not represented in web app, eg doc 0038 - https://github.com/Auden-Musulin-Papers/amp-app/issues/117
- [x] `pb` solution with @prev="true" does not work in doc 0063 - https://github.com/Auden-Musulin-Papers/amp-app/issues/118
- [x] photos (that have no transcription) not displayed in web app, eg docs 0064, 0065 - https://github.com/Auden-Musulin-Papers/amp-app-dev/issues/26#issue-2065164306
- [x] we need `seg` elements to be graphically set apart by new line beginning, eg doc 0004, 0009 - https://github.com/Auden-Musulin-Papers/amp-app-dev/issues/24#issue-2064023595
- [x] we need to show links to authority files in pop-up windows and detail pages of entities - https://github.com/Auden-Musulin-Papers/amp-app/issues/116#issue-2071895723

## questions re TEI solutions (to discuss with @csae8092):
- [x] `<rs target="https://hdl.handle.net/21.11115/0000-000E-C331-E">Auden's letter to Musulin from 24 October 1968</rs>` solution for referencing other AMP documents in a comment, eg in doc 0009 ... better with @source? or with amp_identifier instead of handle, or with `https://id.acdh.oeaw.ac.at/auden-musulin-papers/amp-transcript__0044.xml`?
- [x] `<rs type="person" ref="#amp_person_22"><foreign xml:lang="de"><choice><orig>Burgomeister</orig><reg>Bürgermeister</reg></choice></foreign></rs>` solution for encoding editorial intervention in spelling in text, eg in doc 0009 (less evaluative than `sic`/`corr`?)
- [x] `<ref ana="amp-transcript__0009.xml#ana_012">Of course,<lb/>
                     selfishly, I'm rather reli<unclear><del>v</del></unclear>eved. How horrid<lb/>
                     one is !</ref>` (doc 0010), solution for referring to previous `interp` only if there is no `rs` - similar in doc0053 "zum T." - in other cases we typically have the @ana in `rs` (which is already there)
- [ ] `<bibl sameAs="https://hdl.handle.net/21.11115/0000-000E-C312-1"/>` (doc 0012) solution for referencing other document in TEI formalization of `interp`
in same document: refer to other document through `<rs source="https://hdl.handle.net/21.11115/0000-000E-C312-1">his letter from 4 January 1969</rs>` or via `ref`?
- [ ] ```                                  <bibl type="email">
                                      <author>
                                          <persName ref="#amp_person_94"></persName>
                                      </author>
                                      <title>WG: </title>
                                      <date notBefore-iso="2022-02-15" notAfter-iso="2022-02-15"></date>
                                  </bibl>``` (doc 0053) is this good solution for referencing e-mail

- [ ] `<bibl source="https://de.wikipedia.org/wiki/Schwarzkopf_(Kosmetik)"/>` in doc0053 for a bibliographic reference to a Wikipedia article in the interpretation of `Schuppen-<orig ana="#ana_016">Schaumpon</orig>` in the text
- [ ] ```                        <listBibl>
                           <bibl sameAs="#lit_work_id_45"/>
                           <citedRange unit="page" from="197" to="197"/>
                        </listBibl>``` (in doc 0041, to cite source) for citing a book source with specific page range in the comment that refers to `for the <ref ana="#ana_017">reference to my garage.</ref>` in the text
